name: 'comment-related-issues'
description: 'Comment on Github PR with related issues in your issue trackers.'
inputs:
  tracker:
    description: 'Issue tracker name. Available values are jira'
    required: true
  project-key:
    description: 'Project key like jira project key'
  jira-protocol:
    description: 'Jira protocol. Available values are http and https. Default value is https. Required for Jira.'
    default: 'https'
  jira-host:
    description: 'Jira hostname. Required for Jira.'
  jira-username:
    description: 'Jira username. Required for Jira.'
  jira-token:
    description: 'Jira token from the Jira account. Required for Jira.'
  path:
    description: "Relative path from git repo's root to where you are interested in."
    default: '.'
  include-scope:
    description: "Extract scope from commit messages and include it in the table. Use this when you want to display the scope of commits in the related issues table."
    default: 'false'

outputs:
  success:
    description: 'success'

runs:
  using: 'node20'
  main: 'dist/index.js'
